### ISSUE TITLE
Statistical regions not ignored

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-backend#108] opened 2022-02-07 14:57 UTC
@D063520 @madewild 
In https://kohesio.acceptance.ec.europa.eu/, Project Search, if you select 'Portugal' you got the list of French regions in the regions filter.
Same for Spain. Probably linked to the outermost regions?

**Comment by D063520** [comment] 2022-02-07 15:22
The problem is that many NUTS regions are marked as statistical only and should be ignored. This is not happening. I do not know why. I can currently only check with the help of Raph. I'm waiting for him .....

**Comment by madewild** [comment] 2022-02-07 15:22
Well it's not the French regions (@AThollard you must be tired) but rather a list at a too-high level in the country...
![pt_regions](https://user-images.githubusercontent.com/942488/152817106-3db1478e-9996-4b3c-9d8e-cc8f631aebce.png)

**Comment by madewild** [comment] 2022-02-07 15:26
On https://kohesio.test.ec.europa.eu/projects?tab=results&country=Portugal&sort=Total-Budget-(descending) it works as expected
@raphdom any clue why this is not properly propagated to ACC?

**Comment by AThollard** [comment] 2022-02-07 15:33
> Well it's not the French regions (@AThollard you must be tired ;) ) but rather a list at a too-high level in the country... ![pt_regions](https://user-images.githubusercontent.com/942488/152817106-3db1478e-9996-4b3c-9d8e-cc8f631aebce.png)

Well, starting from scratch in the Project Search I have the French regions both for Portugal and Spain :-)

**Comment by AThollard** [comment] 2022-02-07 15:35
And now no region at all but you are probably working on it.

**Comment by raphdom** [comment] 2022-02-07 15:48
That's a trick one, on acceptance we have the same index as test and I copied the cache also. But it is nice to investigate.

**Comment by madewild** [comment] 2022-02-07 15:56
So basically https://kohesio.acceptance.ec.europa.eu/api/facet/eu/regions?country=https://linkedopendata.eu/entity/Q18 (and same for other countries) is not ignoring statistical NUTS... @raphdom is there a way to give access to @D063520 to debug it?

**Comment by raphdom** [comment] 2022-02-07 16:05
In fact now (that I restart the backend app) we have the right regions for Portugal. We need to investigate more. I am working to have a solution that Dennis can have access to the logs.

**Comment by D063520** [comment] 2022-02-08 12:38
This is fixed, no?

**Comment by madewild** [comment] 2022-02-08 12:39
Yes, let's just make sure we understand why it happened so that it does not happen again ;)

**Closed by madewild** 2022-02-08 12:39 UTC
Labels: bug, acceptance
