### ISSUE TITLE
Nominatim search should be extended with programme region as search area

### ISSUE THREAD

**Issue by saerdnaer** [ec-doris/kohesio-backend#159] opened 2022-03-28 18:13 UTC
It looks like many projects from Niedersachsen (Hamburg) are assigned to Hamburg (Schwaben) in Donau-Ries (Bavaria):

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/40266/160460582-bbf5406f-cc21-42e6-accf-b639cacab9ce.png">

**Comment by madewild** [comment] 2022-09-20 13:09
Difficult issue, postponed again :/

**Comment by saerdnaer** [comment] 2022-09-22 14:40
Can you provide the contact details for the datasource? Maybe they can provide an better export with actual place IDs instead of Strings..

Also if you could elaborate on your concrete Nominatim queries, I actual might be able to help... :-)

**Comment by madewild** [comment] 2022-12-07 10:22
We have an idea to improve it but could not implement it in time for this release... We will tackle this with NUTS-related issues early next year

**Comment by madewild** [comment] 2024-09-03 14:18
@DiaZork this has been open for a long time, any update?

**Comment by DiaZork** [comment] 2024-09-05 11:28
I think this is more a topic on when we inject the data in the wikibase when we try to find the coordinates from the location given by the managing authorities.

**Comment by madewild** [comment] 2024-10-01 08:02
@Dgojsic any opinion on that? should we close or move to the data part?

**Comment by Dgojsic** [comment] 2024-10-01 09:12
Definately a data problem, already encountered this myself. Not one we can fully fix though. The issue is that German MAs literally only give you one piece of text as the location indicator, and  there are often multiple cities with the same name in Germany. As Germany's OPs are basically divided by NUTS1, I will add it for each OP the next time we update the country so at least we find the correct city within a Land, and not completely at the other end of the country.

**Comment by D063520** [comment] 2024-10-01 20:05
You took over the data ingestion. So we cannot address this anymore. I would close it here ....

**Closed** 2024-10-02 07:08 UTC
Labels: bug, good first issue
